name: Promote to Prod
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Deploy static site from test to prod S3
      run: aws s3 sync s3://static-site-test-accepted-tortoise s3://d3ip-public-website-prod --delete
    - name: Invalidate cloudfront cache
      run: aws cloudfront create-invalidation --distribution-id EFYUK8T9OZTEA --paths "/*"
